/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PixOrderIdRouteImport } from './routes/pix.$orderId'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as PagamentoConfirmadoOrderIdRouteImport } from './routes/pagamento-confirmado.$orderId'
import { Route as ApiPublicRevealKeyRouteImport } from './routes/api/public/reveal-key'

const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PixOrderIdRoute = PixOrderIdRouteImport.update({
  id: '/pix/$orderId',
  path: '/pix/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmadoOrderIdRoute =
  PagamentoConfirmadoOrderIdRouteImport.update({
    id: '/pagamento-confirmado/$orderId',
    path: '/pagamento-confirmado/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevealKeyRoute = ApiPublicRevealKeyRouteImport.update({
  id: '/api/public/reveal-key',
  path: '/api/public/reveal-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedidos': typeof PedidosRoute
  '/pagamento-confirmado/$orderId': typeof PagamentoConfirmadoOrderIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/pix/$orderId': typeof PixOrderIdRoute
  '/api/public/reveal-key': typeof ApiPublicRevealKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedidos': typeof PedidosRoute
  '/pagamento-confirmado/$orderId': typeof PagamentoConfirmadoOrderIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/pix/$orderId': typeof PixOrderIdRoute
  '/api/public/reveal-key': typeof ApiPublicRevealKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedidos': typeof PedidosRoute
  '/pagamento-confirmado/$orderId': typeof PagamentoConfirmadoOrderIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/pix/$orderId': typeof PixOrderIdRoute
  '/api/public/reveal-key': typeof ApiPublicRevealKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/pedidos'
    | '/pagamento-confirmado/$orderId'
    | '/pedido/$orderId'
    | '/pix/$orderId'
    | '/api/public/reveal-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/pedidos'
    | '/pagamento-confirmado/$orderId'
    | '/pedido/$orderId'
    | '/pix/$orderId'
    | '/api/public/reveal-key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/minha-conta'
    | '/pedidos'
    | '/pagamento-confirmado/$orderId'
    | '/pedido/$orderId'
    | '/pix/$orderId'
    | '/api/public/reveal-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PedidosRoute: typeof PedidosRoute
  PagamentoConfirmadoOrderIdRoute: typeof PagamentoConfirmadoOrderIdRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  PixOrderIdRoute: typeof PixOrderIdRoute
  ApiPublicRevealKeyRoute: typeof ApiPublicRevealKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix/$orderId': {
      id: '/pix/$orderId'
      path: '/pix/$orderId'
      fullPath: '/pix/$orderId'
      preLoaderRoute: typeof PixOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado/$orderId': {
      id: '/pagamento-confirmado/$orderId'
      path: '/pagamento-confirmado/$orderId'
      fullPath: '/pagamento-confirmado/$orderId'
      preLoaderRoute: typeof PagamentoConfirmadoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reveal-key': {
      id: '/api/public/reveal-key'
      path: '/api/public/reveal-key'
      fullPath: '/api/public/reveal-key'
      preLoaderRoute: typeof ApiPublicRevealKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  MinhaContaRoute: MinhaContaRoute,
  PedidosRoute: PedidosRoute,
  PagamentoConfirmadoOrderIdRoute: PagamentoConfirmadoOrderIdRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  PixOrderIdRoute: PixOrderIdRoute,
  ApiPublicRevealKeyRoute: ApiPublicRevealKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
